/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportCenterDataRouteImport } from './routes/support-center-data'
import { Route as SupportCenterRouteImport } from './routes/support-center'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as EmployerIndexRouteImport } from './routes/employer/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EmployerWalletRouteImport } from './routes/employer/wallet'
import { Route as EmployerVnpayReturnRouteImport } from './routes/employer/vnpay-return'
import { Route as EmployerVerificationRouteImport } from './routes/employer/verification'
import { Route as EmployerShiftManagementRouteImport } from './routes/employer/shift-management'
import { Route as EmployerQrDisplayRouteImport } from './routes/employer/qr-display'
import { Route as EmployerProfileRouteImport } from './routes/employer/profile'
import { Route as EmployerPostJobRouteImport } from './routes/employer/post-job'
import { Route as EmployerNotificationsRouteImport } from './routes/employer/notifications'
import { Route as EmployerJobListRouteImport } from './routes/employer/job-list'
import { Route as EmployerJobDetailRouteImport } from './routes/employer/job-detail'
import { Route as EmployerChatRouteImport } from './routes/employer/chat'
import { Route as EmployerApplicantsRouteImport } from './routes/employer/applicants'
import { Route as CandidateWishlistRouteImport } from './routes/candidate/wishlist'
import { Route as CandidateWalletRouteImport } from './routes/candidate/wallet'
import { Route as CandidateShiftsRouteImport } from './routes/candidate/shifts'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate/notifications'
import { Route as CandidateChatRouteImport } from './routes/candidate/chat'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate/applications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as EmployerVerificationIndexRouteImport } from './routes/employer/verification/index'
import { Route as EmployerProfileIndexRouteImport } from './routes/employer/profile/index'
import { Route as CandidateVerificationIndexRouteImport } from './routes/candidate/verification/index'
import { Route as CandidateProfileIndexRouteImport } from './routes/candidate/profile/index'
import { Route as EmployerProfileReputationRouteImport } from './routes/employer/profile/reputation'
import { Route as EmployerProfileEditRouteImport } from './routes/employer/profile/edit'
import { Route as EmployerCandidateCandidateIdRouteImport } from './routes/employer/candidate.$candidateId'
import { Route as CandidateProfileVerifyRouteImport } from './routes/candidate/profile/verify'
import { Route as CandidateProfileSettingsRouteImport } from './routes/candidate/profile/settings'
import { Route as CandidateProfileReputationRouteImport } from './routes/candidate/profile/reputation'
import { Route as CandidateProfileEditRouteImport } from './routes/candidate/profile/edit'
import { Route as CandidateJobsJobIdRouteImport } from './routes/candidate/jobs/$jobId'
import { Route as CandidateEmployerEmployerIdRouteImport } from './routes/candidate/employer/$employerId'
import { Route as CandidateApplicationsApplicationIdRouteImport } from './routes/candidate/applications.$applicationId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as EmployerProfileSettingsIndexRouteImport } from './routes/employer/profile/settings/index'
import { Route as EmployerProfileSettingsTermsRouteImport } from './routes/employer/profile/settings/terms'
import { Route as EmployerProfileSettingsPrivacyRouteImport } from './routes/employer/profile/settings/privacy'
import { Route as EmployerProfileSettingsPhoneRouteImport } from './routes/employer/profile/settings/phone'
import { Route as EmployerProfileSettingsPasswordRouteImport } from './routes/employer/profile/settings/password'
import { Route as EmployerProfileSettingsDevicesRouteImport } from './routes/employer/profile/settings/devices'
import { Route as EmployerProfileSettingsDeleteRouteImport } from './routes/employer/profile/settings/delete'
import { Route as EmployerProfileSettingsDeactivateRouteImport } from './routes/employer/profile/settings/deactivate'

const SupportCenterDataRoute = SupportCenterDataRouteImport.update({
  id: '/support-center-data',
  path: '/support-center-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCenterRoute = SupportCenterRouteImport.update({
  id: '/support-center',
  path: '/support-center',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmployerWalletRoute = EmployerWalletRouteImport.update({
  id: '/employer/wallet',
  path: '/employer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerVnpayReturnRoute = EmployerVnpayReturnRouteImport.update({
  id: '/employer/vnpay-return',
  path: '/employer/vnpay-return',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerVerificationRoute = EmployerVerificationRouteImport.update({
  id: '/employer/verification',
  path: '/employer/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerShiftManagementRoute = EmployerShiftManagementRouteImport.update({
  id: '/employer/shift-management',
  path: '/employer/shift-management',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerQrDisplayRoute = EmployerQrDisplayRouteImport.update({
  id: '/employer/qr-display',
  path: '/employer/qr-display',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer/profile',
  path: '/employer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPostJobRoute = EmployerPostJobRouteImport.update({
  id: '/employer/post-job',
  path: '/employer/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerNotificationsRoute = EmployerNotificationsRouteImport.update({
  id: '/employer/notifications',
  path: '/employer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobListRoute = EmployerJobListRouteImport.update({
  id: '/employer/job-list',
  path: '/employer/job-list',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobDetailRoute = EmployerJobDetailRouteImport.update({
  id: '/employer/job-detail',
  path: '/employer/job-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerChatRoute = EmployerChatRouteImport.update({
  id: '/employer/chat',
  path: '/employer/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicantsRoute = EmployerApplicantsRouteImport.update({
  id: '/employer/applicants',
  path: '/employer/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateWishlistRoute = CandidateWishlistRouteImport.update({
  id: '/candidate/wishlist',
  path: '/candidate/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateWalletRoute = CandidateWalletRouteImport.update({
  id: '/candidate/wallet',
  path: '/candidate/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateShiftsRoute = CandidateShiftsRouteImport.update({
  id: '/candidate/shifts',
  path: '/candidate/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateChatRoute = CandidateChatRouteImport.update({
  id: '/candidate/chat',
  path: '/candidate/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const EmployerVerificationIndexRoute =
  EmployerVerificationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmployerVerificationRoute,
  } as any)
const EmployerProfileIndexRoute = EmployerProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerProfileRoute,
} as any)
const CandidateVerificationIndexRoute =
  CandidateVerificationIndexRouteImport.update({
    id: '/candidate/verification/',
    path: '/candidate/verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateProfileIndexRoute = CandidateProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateProfileRoute,
} as any)
const EmployerProfileReputationRoute =
  EmployerProfileReputationRouteImport.update({
    id: '/reputation',
    path: '/reputation',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileEditRoute = EmployerProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EmployerProfileRoute,
} as any)
const EmployerCandidateCandidateIdRoute =
  EmployerCandidateCandidateIdRouteImport.update({
    id: '/employer/candidate/$candidateId',
    path: '/employer/candidate/$candidateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateProfileVerifyRoute = CandidateProfileVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => CandidateProfileRoute,
} as any)
const CandidateProfileSettingsRoute =
  CandidateProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CandidateProfileRoute,
  } as any)
const CandidateProfileReputationRoute =
  CandidateProfileReputationRouteImport.update({
    id: '/reputation',
    path: '/reputation',
    getParentRoute: () => CandidateProfileRoute,
  } as any)
const CandidateProfileEditRoute = CandidateProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CandidateProfileRoute,
} as any)
const CandidateJobsJobIdRoute = CandidateJobsJobIdRouteImport.update({
  id: '/candidate/jobs/$jobId',
  path: '/candidate/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateEmployerEmployerIdRoute =
  CandidateEmployerEmployerIdRouteImport.update({
    id: '/candidate/employer/$employerId',
    path: '/candidate/employer/$employerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateApplicationsApplicationIdRoute =
  CandidateApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => CandidateApplicationsRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const EmployerProfileSettingsIndexRoute =
  EmployerProfileSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsTermsRoute =
  EmployerProfileSettingsTermsRouteImport.update({
    id: '/settings/terms',
    path: '/settings/terms',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsPrivacyRoute =
  EmployerProfileSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsPhoneRoute =
  EmployerProfileSettingsPhoneRouteImport.update({
    id: '/settings/phone',
    path: '/settings/phone',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsPasswordRoute =
  EmployerProfileSettingsPasswordRouteImport.update({
    id: '/settings/password',
    path: '/settings/password',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsDevicesRoute =
  EmployerProfileSettingsDevicesRouteImport.update({
    id: '/settings/devices',
    path: '/settings/devices',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsDeleteRoute =
  EmployerProfileSettingsDeleteRouteImport.update({
    id: '/settings/delete',
    path: '/settings/delete',
    getParentRoute: () => EmployerProfileRoute,
  } as any)
const EmployerProfileSettingsDeactivateRoute =
  EmployerProfileSettingsDeactivateRouteImport.update({
    id: '/settings/deactivate',
    path: '/settings/deactivate',
    getParentRoute: () => EmployerProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRouteWithChildren
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRouteWithChildren
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/candidate/wallet': typeof CandidateWalletRoute
  '/candidate/wishlist': typeof CandidateWishlistRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/job-detail': typeof EmployerJobDetailRoute
  '/employer/job-list': typeof EmployerJobListRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/profile': typeof EmployerProfileRouteWithChildren
  '/employer/qr-display': typeof EmployerQrDisplayRoute
  '/employer/shift-management': typeof EmployerShiftManagementRoute
  '/employer/verification': typeof EmployerVerificationRouteWithChildren
  '/employer/vnpay-return': typeof EmployerVnpayReturnRoute
  '/employer/wallet': typeof EmployerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/employer/$employerId': typeof CandidateEmployerEmployerIdRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/candidate/profile/edit': typeof CandidateProfileEditRoute
  '/candidate/profile/reputation': typeof CandidateProfileReputationRoute
  '/candidate/profile/settings': typeof CandidateProfileSettingsRoute
  '/candidate/profile/verify': typeof CandidateProfileVerifyRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/profile/edit': typeof EmployerProfileEditRoute
  '/employer/profile/reputation': typeof EmployerProfileReputationRoute
  '/candidate/profile/': typeof CandidateProfileIndexRoute
  '/candidate/verification/': typeof CandidateVerificationIndexRoute
  '/employer/profile/': typeof EmployerProfileIndexRoute
  '/employer/verification/': typeof EmployerVerificationIndexRoute
  '/employer/profile/settings/deactivate': typeof EmployerProfileSettingsDeactivateRoute
  '/employer/profile/settings/delete': typeof EmployerProfileSettingsDeleteRoute
  '/employer/profile/settings/devices': typeof EmployerProfileSettingsDevicesRoute
  '/employer/profile/settings/password': typeof EmployerProfileSettingsPasswordRoute
  '/employer/profile/settings/phone': typeof EmployerProfileSettingsPhoneRoute
  '/employer/profile/settings/privacy': typeof EmployerProfileSettingsPrivacyRoute
  '/employer/profile/settings/terms': typeof EmployerProfileSettingsTermsRoute
  '/employer/profile/settings/': typeof EmployerProfileSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRouteWithChildren
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/candidate/wallet': typeof CandidateWalletRoute
  '/candidate/wishlist': typeof CandidateWishlistRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/job-detail': typeof EmployerJobDetailRoute
  '/employer/job-list': typeof EmployerJobListRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/qr-display': typeof EmployerQrDisplayRoute
  '/employer/shift-management': typeof EmployerShiftManagementRoute
  '/employer/vnpay-return': typeof EmployerVnpayReturnRoute
  '/employer/wallet': typeof EmployerWalletRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/employer/$employerId': typeof CandidateEmployerEmployerIdRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/candidate/profile/edit': typeof CandidateProfileEditRoute
  '/candidate/profile/reputation': typeof CandidateProfileReputationRoute
  '/candidate/profile/settings': typeof CandidateProfileSettingsRoute
  '/candidate/profile/verify': typeof CandidateProfileVerifyRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/profile/edit': typeof EmployerProfileEditRoute
  '/employer/profile/reputation': typeof EmployerProfileReputationRoute
  '/candidate/profile': typeof CandidateProfileIndexRoute
  '/candidate/verification': typeof CandidateVerificationIndexRoute
  '/employer/profile': typeof EmployerProfileIndexRoute
  '/employer/verification': typeof EmployerVerificationIndexRoute
  '/employer/profile/settings/deactivate': typeof EmployerProfileSettingsDeactivateRoute
  '/employer/profile/settings/delete': typeof EmployerProfileSettingsDeleteRoute
  '/employer/profile/settings/devices': typeof EmployerProfileSettingsDevicesRoute
  '/employer/profile/settings/password': typeof EmployerProfileSettingsPasswordRoute
  '/employer/profile/settings/phone': typeof EmployerProfileSettingsPhoneRoute
  '/employer/profile/settings/privacy': typeof EmployerProfileSettingsPrivacyRoute
  '/employer/profile/settings/terms': typeof EmployerProfileSettingsTermsRoute
  '/employer/profile/settings': typeof EmployerProfileSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRouteWithChildren
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRouteWithChildren
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/candidate/wallet': typeof CandidateWalletRoute
  '/candidate/wishlist': typeof CandidateWishlistRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/job-detail': typeof EmployerJobDetailRoute
  '/employer/job-list': typeof EmployerJobListRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/profile': typeof EmployerProfileRouteWithChildren
  '/employer/qr-display': typeof EmployerQrDisplayRoute
  '/employer/shift-management': typeof EmployerShiftManagementRoute
  '/employer/verification': typeof EmployerVerificationRouteWithChildren
  '/employer/vnpay-return': typeof EmployerVnpayReturnRoute
  '/employer/wallet': typeof EmployerWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/employer/$employerId': typeof CandidateEmployerEmployerIdRoute
  '/candidate/jobs/$jobId': typeof CandidateJobsJobIdRoute
  '/candidate/profile/edit': typeof CandidateProfileEditRoute
  '/candidate/profile/reputation': typeof CandidateProfileReputationRoute
  '/candidate/profile/settings': typeof CandidateProfileSettingsRoute
  '/candidate/profile/verify': typeof CandidateProfileVerifyRoute
  '/employer/candidate/$candidateId': typeof EmployerCandidateCandidateIdRoute
  '/employer/profile/edit': typeof EmployerProfileEditRoute
  '/employer/profile/reputation': typeof EmployerProfileReputationRoute
  '/candidate/profile/': typeof CandidateProfileIndexRoute
  '/candidate/verification/': typeof CandidateVerificationIndexRoute
  '/employer/profile/': typeof EmployerProfileIndexRoute
  '/employer/verification/': typeof EmployerVerificationIndexRoute
  '/employer/profile/settings/deactivate': typeof EmployerProfileSettingsDeactivateRoute
  '/employer/profile/settings/delete': typeof EmployerProfileSettingsDeleteRoute
  '/employer/profile/settings/devices': typeof EmployerProfileSettingsDevicesRoute
  '/employer/profile/settings/password': typeof EmployerProfileSettingsPasswordRoute
  '/employer/profile/settings/phone': typeof EmployerProfileSettingsPhoneRoute
  '/employer/profile/settings/privacy': typeof EmployerProfileSettingsPrivacyRoute
  '/employer/profile/settings/terms': typeof EmployerProfileSettingsTermsRoute
  '/employer/profile/settings/': typeof EmployerProfileSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applications'
    | '/candidate/chat'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/shifts'
    | '/candidate/wallet'
    | '/candidate/wishlist'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/job-detail'
    | '/employer/job-list'
    | '/employer/notifications'
    | '/employer/post-job'
    | '/employer/profile'
    | '/employer/qr-display'
    | '/employer/shift-management'
    | '/employer/verification'
    | '/employer/vnpay-return'
    | '/employer/wallet'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/jobs/'
    | '/admin/users/$userId'
    | '/candidate/applications/$applicationId'
    | '/candidate/employer/$employerId'
    | '/candidate/jobs/$jobId'
    | '/candidate/profile/edit'
    | '/candidate/profile/reputation'
    | '/candidate/profile/settings'
    | '/candidate/profile/verify'
    | '/employer/candidate/$candidateId'
    | '/employer/profile/edit'
    | '/employer/profile/reputation'
    | '/candidate/profile/'
    | '/candidate/verification/'
    | '/employer/profile/'
    | '/employer/verification/'
    | '/employer/profile/settings/deactivate'
    | '/employer/profile/settings/delete'
    | '/employer/profile/settings/devices'
    | '/employer/profile/settings/password'
    | '/employer/profile/settings/phone'
    | '/employer/profile/settings/privacy'
    | '/employer/profile/settings/terms'
    | '/employer/profile/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applications'
    | '/candidate/chat'
    | '/candidate/notifications'
    | '/candidate/shifts'
    | '/candidate/wallet'
    | '/candidate/wishlist'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/job-detail'
    | '/employer/job-list'
    | '/employer/notifications'
    | '/employer/post-job'
    | '/employer/qr-display'
    | '/employer/shift-management'
    | '/employer/vnpay-return'
    | '/employer/wallet'
    | '/admin'
    | '/candidate'
    | '/employer'
    | '/jobs'
    | '/admin/users/$userId'
    | '/candidate/applications/$applicationId'
    | '/candidate/employer/$employerId'
    | '/candidate/jobs/$jobId'
    | '/candidate/profile/edit'
    | '/candidate/profile/reputation'
    | '/candidate/profile/settings'
    | '/candidate/profile/verify'
    | '/employer/candidate/$candidateId'
    | '/employer/profile/edit'
    | '/employer/profile/reputation'
    | '/candidate/profile'
    | '/candidate/verification'
    | '/employer/profile'
    | '/employer/verification'
    | '/employer/profile/settings/deactivate'
    | '/employer/profile/settings/delete'
    | '/employer/profile/settings/devices'
    | '/employer/profile/settings/password'
    | '/employer/profile/settings/phone'
    | '/employer/profile/settings/privacy'
    | '/employer/profile/settings/terms'
    | '/employer/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/applications'
    | '/candidate/chat'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/shifts'
    | '/candidate/wallet'
    | '/candidate/wishlist'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/job-detail'
    | '/employer/job-list'
    | '/employer/notifications'
    | '/employer/post-job'
    | '/employer/profile'
    | '/employer/qr-display'
    | '/employer/shift-management'
    | '/employer/verification'
    | '/employer/vnpay-return'
    | '/employer/wallet'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/jobs/'
    | '/admin/users/$userId'
    | '/candidate/applications/$applicationId'
    | '/candidate/employer/$employerId'
    | '/candidate/jobs/$jobId'
    | '/candidate/profile/edit'
    | '/candidate/profile/reputation'
    | '/candidate/profile/settings'
    | '/candidate/profile/verify'
    | '/employer/candidate/$candidateId'
    | '/employer/profile/edit'
    | '/employer/profile/reputation'
    | '/candidate/profile/'
    | '/candidate/verification/'
    | '/employer/profile/'
    | '/employer/verification/'
    | '/employer/profile/settings/deactivate'
    | '/employer/profile/settings/delete'
    | '/employer/profile/settings/devices'
    | '/employer/profile/settings/password'
    | '/employer/profile/settings/phone'
    | '/employer/profile/settings/privacy'
    | '/employer/profile/settings/terms'
    | '/employer/profile/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SupportCenterRoute: typeof SupportCenterRoute
  SupportCenterDataRoute: typeof SupportCenterDataRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRouteWithChildren
  CandidateChatRoute: typeof CandidateChatRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRouteWithChildren
  CandidateShiftsRoute: typeof CandidateShiftsRoute
  CandidateWalletRoute: typeof CandidateWalletRoute
  CandidateWishlistRoute: typeof CandidateWishlistRoute
  EmployerApplicantsRoute: typeof EmployerApplicantsRoute
  EmployerChatRoute: typeof EmployerChatRoute
  EmployerJobDetailRoute: typeof EmployerJobDetailRoute
  EmployerJobListRoute: typeof EmployerJobListRoute
  EmployerNotificationsRoute: typeof EmployerNotificationsRoute
  EmployerPostJobRoute: typeof EmployerPostJobRoute
  EmployerProfileRoute: typeof EmployerProfileRouteWithChildren
  EmployerQrDisplayRoute: typeof EmployerQrDisplayRoute
  EmployerShiftManagementRoute: typeof EmployerShiftManagementRoute
  EmployerVerificationRoute: typeof EmployerVerificationRouteWithChildren
  EmployerVnpayReturnRoute: typeof EmployerVnpayReturnRoute
  EmployerWalletRoute: typeof EmployerWalletRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  CandidateEmployerEmployerIdRoute: typeof CandidateEmployerEmployerIdRoute
  CandidateJobsJobIdRoute: typeof CandidateJobsJobIdRoute
  EmployerCandidateCandidateIdRoute: typeof EmployerCandidateCandidateIdRoute
  CandidateVerificationIndexRoute: typeof CandidateVerificationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-center-data': {
      id: '/support-center-data'
      path: '/support-center-data'
      fullPath: '/support-center-data'
      preLoaderRoute: typeof SupportCenterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-center': {
      id: '/support-center'
      path: '/support-center'
      fullPath: '/support-center'
      preLoaderRoute: typeof SupportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employer/wallet': {
      id: '/employer/wallet'
      path: '/employer/wallet'
      fullPath: '/employer/wallet'
      preLoaderRoute: typeof EmployerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vnpay-return': {
      id: '/employer/vnpay-return'
      path: '/employer/vnpay-return'
      fullPath: '/employer/vnpay-return'
      preLoaderRoute: typeof EmployerVnpayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/verification': {
      id: '/employer/verification'
      path: '/employer/verification'
      fullPath: '/employer/verification'
      preLoaderRoute: typeof EmployerVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/shift-management': {
      id: '/employer/shift-management'
      path: '/employer/shift-management'
      fullPath: '/employer/shift-management'
      preLoaderRoute: typeof EmployerShiftManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/qr-display': {
      id: '/employer/qr-display'
      path: '/employer/qr-display'
      fullPath: '/employer/qr-display'
      preLoaderRoute: typeof EmployerQrDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/profile': {
      id: '/employer/profile'
      path: '/employer/profile'
      fullPath: '/employer/profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/post-job': {
      id: '/employer/post-job'
      path: '/employer/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof EmployerPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/notifications': {
      id: '/employer/notifications'
      path: '/employer/notifications'
      fullPath: '/employer/notifications'
      preLoaderRoute: typeof EmployerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/job-list': {
      id: '/employer/job-list'
      path: '/employer/job-list'
      fullPath: '/employer/job-list'
      preLoaderRoute: typeof EmployerJobListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/job-detail': {
      id: '/employer/job-detail'
      path: '/employer/job-detail'
      fullPath: '/employer/job-detail'
      preLoaderRoute: typeof EmployerJobDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/chat': {
      id: '/employer/chat'
      path: '/employer/chat'
      fullPath: '/employer/chat'
      preLoaderRoute: typeof EmployerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applicants': {
      id: '/employer/applicants'
      path: '/employer/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof EmployerApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/wishlist': {
      id: '/candidate/wishlist'
      path: '/candidate/wishlist'
      fullPath: '/candidate/wishlist'
      preLoaderRoute: typeof CandidateWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/wallet': {
      id: '/candidate/wallet'
      path: '/candidate/wallet'
      fullPath: '/candidate/wallet'
      preLoaderRoute: typeof CandidateWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/shifts': {
      id: '/candidate/shifts'
      path: '/candidate/shifts'
      fullPath: '/candidate/shifts'
      preLoaderRoute: typeof CandidateShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/chat': {
      id: '/candidate/chat'
      path: '/candidate/chat'
      fullPath: '/candidate/chat'
      preLoaderRoute: typeof CandidateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employer/verification/': {
      id: '/employer/verification/'
      path: '/'
      fullPath: '/employer/verification/'
      preLoaderRoute: typeof EmployerVerificationIndexRouteImport
      parentRoute: typeof EmployerVerificationRoute
    }
    '/employer/profile/': {
      id: '/employer/profile/'
      path: '/'
      fullPath: '/employer/profile/'
      preLoaderRoute: typeof EmployerProfileIndexRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/candidate/verification/': {
      id: '/candidate/verification/'
      path: '/candidate/verification'
      fullPath: '/candidate/verification/'
      preLoaderRoute: typeof CandidateVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile/': {
      id: '/candidate/profile/'
      path: '/'
      fullPath: '/candidate/profile/'
      preLoaderRoute: typeof CandidateProfileIndexRouteImport
      parentRoute: typeof CandidateProfileRoute
    }
    '/employer/profile/reputation': {
      id: '/employer/profile/reputation'
      path: '/reputation'
      fullPath: '/employer/profile/reputation'
      preLoaderRoute: typeof EmployerProfileReputationRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/edit': {
      id: '/employer/profile/edit'
      path: '/edit'
      fullPath: '/employer/profile/edit'
      preLoaderRoute: typeof EmployerProfileEditRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/candidate/$candidateId': {
      id: '/employer/candidate/$candidateId'
      path: '/employer/candidate/$candidateId'
      fullPath: '/employer/candidate/$candidateId'
      preLoaderRoute: typeof EmployerCandidateCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile/verify': {
      id: '/candidate/profile/verify'
      path: '/verify'
      fullPath: '/candidate/profile/verify'
      preLoaderRoute: typeof CandidateProfileVerifyRouteImport
      parentRoute: typeof CandidateProfileRoute
    }
    '/candidate/profile/settings': {
      id: '/candidate/profile/settings'
      path: '/settings'
      fullPath: '/candidate/profile/settings'
      preLoaderRoute: typeof CandidateProfileSettingsRouteImport
      parentRoute: typeof CandidateProfileRoute
    }
    '/candidate/profile/reputation': {
      id: '/candidate/profile/reputation'
      path: '/reputation'
      fullPath: '/candidate/profile/reputation'
      preLoaderRoute: typeof CandidateProfileReputationRouteImport
      parentRoute: typeof CandidateProfileRoute
    }
    '/candidate/profile/edit': {
      id: '/candidate/profile/edit'
      path: '/edit'
      fullPath: '/candidate/profile/edit'
      preLoaderRoute: typeof CandidateProfileEditRouteImport
      parentRoute: typeof CandidateProfileRoute
    }
    '/candidate/jobs/$jobId': {
      id: '/candidate/jobs/$jobId'
      path: '/candidate/jobs/$jobId'
      fullPath: '/candidate/jobs/$jobId'
      preLoaderRoute: typeof CandidateJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/employer/$employerId': {
      id: '/candidate/employer/$employerId'
      path: '/candidate/employer/$employerId'
      fullPath: '/candidate/employer/$employerId'
      preLoaderRoute: typeof CandidateEmployerEmployerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications/$applicationId': {
      id: '/candidate/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/candidate/applications/$applicationId'
      preLoaderRoute: typeof CandidateApplicationsApplicationIdRouteImport
      parentRoute: typeof CandidateApplicationsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/employer/profile/settings/': {
      id: '/employer/profile/settings/'
      path: '/settings'
      fullPath: '/employer/profile/settings/'
      preLoaderRoute: typeof EmployerProfileSettingsIndexRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/terms': {
      id: '/employer/profile/settings/terms'
      path: '/settings/terms'
      fullPath: '/employer/profile/settings/terms'
      preLoaderRoute: typeof EmployerProfileSettingsTermsRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/privacy': {
      id: '/employer/profile/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/employer/profile/settings/privacy'
      preLoaderRoute: typeof EmployerProfileSettingsPrivacyRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/phone': {
      id: '/employer/profile/settings/phone'
      path: '/settings/phone'
      fullPath: '/employer/profile/settings/phone'
      preLoaderRoute: typeof EmployerProfileSettingsPhoneRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/password': {
      id: '/employer/profile/settings/password'
      path: '/settings/password'
      fullPath: '/employer/profile/settings/password'
      preLoaderRoute: typeof EmployerProfileSettingsPasswordRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/devices': {
      id: '/employer/profile/settings/devices'
      path: '/settings/devices'
      fullPath: '/employer/profile/settings/devices'
      preLoaderRoute: typeof EmployerProfileSettingsDevicesRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/delete': {
      id: '/employer/profile/settings/delete'
      path: '/settings/delete'
      fullPath: '/employer/profile/settings/delete'
      preLoaderRoute: typeof EmployerProfileSettingsDeleteRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
    '/employer/profile/settings/deactivate': {
      id: '/employer/profile/settings/deactivate'
      path: '/settings/deactivate'
      fullPath: '/employer/profile/settings/deactivate'
      preLoaderRoute: typeof EmployerProfileSettingsDeactivateRouteImport
      parentRoute: typeof EmployerProfileRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CandidateApplicationsRouteChildren {
  CandidateApplicationsApplicationIdRoute: typeof CandidateApplicationsApplicationIdRoute
}

const CandidateApplicationsRouteChildren: CandidateApplicationsRouteChildren = {
  CandidateApplicationsApplicationIdRoute:
    CandidateApplicationsApplicationIdRoute,
}

const CandidateApplicationsRouteWithChildren =
  CandidateApplicationsRoute._addFileChildren(
    CandidateApplicationsRouteChildren,
  )

interface CandidateProfileRouteChildren {
  CandidateProfileEditRoute: typeof CandidateProfileEditRoute
  CandidateProfileReputationRoute: typeof CandidateProfileReputationRoute
  CandidateProfileSettingsRoute: typeof CandidateProfileSettingsRoute
  CandidateProfileVerifyRoute: typeof CandidateProfileVerifyRoute
  CandidateProfileIndexRoute: typeof CandidateProfileIndexRoute
}

const CandidateProfileRouteChildren: CandidateProfileRouteChildren = {
  CandidateProfileEditRoute: CandidateProfileEditRoute,
  CandidateProfileReputationRoute: CandidateProfileReputationRoute,
  CandidateProfileSettingsRoute: CandidateProfileSettingsRoute,
  CandidateProfileVerifyRoute: CandidateProfileVerifyRoute,
  CandidateProfileIndexRoute: CandidateProfileIndexRoute,
}

const CandidateProfileRouteWithChildren =
  CandidateProfileRoute._addFileChildren(CandidateProfileRouteChildren)

interface EmployerProfileRouteChildren {
  EmployerProfileEditRoute: typeof EmployerProfileEditRoute
  EmployerProfileReputationRoute: typeof EmployerProfileReputationRoute
  EmployerProfileIndexRoute: typeof EmployerProfileIndexRoute
  EmployerProfileSettingsDeactivateRoute: typeof EmployerProfileSettingsDeactivateRoute
  EmployerProfileSettingsDeleteRoute: typeof EmployerProfileSettingsDeleteRoute
  EmployerProfileSettingsDevicesRoute: typeof EmployerProfileSettingsDevicesRoute
  EmployerProfileSettingsPasswordRoute: typeof EmployerProfileSettingsPasswordRoute
  EmployerProfileSettingsPhoneRoute: typeof EmployerProfileSettingsPhoneRoute
  EmployerProfileSettingsPrivacyRoute: typeof EmployerProfileSettingsPrivacyRoute
  EmployerProfileSettingsTermsRoute: typeof EmployerProfileSettingsTermsRoute
  EmployerProfileSettingsIndexRoute: typeof EmployerProfileSettingsIndexRoute
}

const EmployerProfileRouteChildren: EmployerProfileRouteChildren = {
  EmployerProfileEditRoute: EmployerProfileEditRoute,
  EmployerProfileReputationRoute: EmployerProfileReputationRoute,
  EmployerProfileIndexRoute: EmployerProfileIndexRoute,
  EmployerProfileSettingsDeactivateRoute:
    EmployerProfileSettingsDeactivateRoute,
  EmployerProfileSettingsDeleteRoute: EmployerProfileSettingsDeleteRoute,
  EmployerProfileSettingsDevicesRoute: EmployerProfileSettingsDevicesRoute,
  EmployerProfileSettingsPasswordRoute: EmployerProfileSettingsPasswordRoute,
  EmployerProfileSettingsPhoneRoute: EmployerProfileSettingsPhoneRoute,
  EmployerProfileSettingsPrivacyRoute: EmployerProfileSettingsPrivacyRoute,
  EmployerProfileSettingsTermsRoute: EmployerProfileSettingsTermsRoute,
  EmployerProfileSettingsIndexRoute: EmployerProfileSettingsIndexRoute,
}

const EmployerProfileRouteWithChildren = EmployerProfileRoute._addFileChildren(
  EmployerProfileRouteChildren,
)

interface EmployerVerificationRouteChildren {
  EmployerVerificationIndexRoute: typeof EmployerVerificationIndexRoute
}

const EmployerVerificationRouteChildren: EmployerVerificationRouteChildren = {
  EmployerVerificationIndexRoute: EmployerVerificationIndexRoute,
}

const EmployerVerificationRouteWithChildren =
  EmployerVerificationRoute._addFileChildren(EmployerVerificationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SupportCenterRoute: SupportCenterRoute,
  SupportCenterDataRoute: SupportCenterDataRoute,
  CandidateApplicationsRoute: CandidateApplicationsRouteWithChildren,
  CandidateChatRoute: CandidateChatRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRouteWithChildren,
  CandidateShiftsRoute: CandidateShiftsRoute,
  CandidateWalletRoute: CandidateWalletRoute,
  CandidateWishlistRoute: CandidateWishlistRoute,
  EmployerApplicantsRoute: EmployerApplicantsRoute,
  EmployerChatRoute: EmployerChatRoute,
  EmployerJobDetailRoute: EmployerJobDetailRoute,
  EmployerJobListRoute: EmployerJobListRoute,
  EmployerNotificationsRoute: EmployerNotificationsRoute,
  EmployerPostJobRoute: EmployerPostJobRoute,
  EmployerProfileRoute: EmployerProfileRouteWithChildren,
  EmployerQrDisplayRoute: EmployerQrDisplayRoute,
  EmployerShiftManagementRoute: EmployerShiftManagementRoute,
  EmployerVerificationRoute: EmployerVerificationRouteWithChildren,
  EmployerVnpayReturnRoute: EmployerVnpayReturnRoute,
  EmployerWalletRoute: EmployerWalletRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  CandidateEmployerEmployerIdRoute: CandidateEmployerEmployerIdRoute,
  CandidateJobsJobIdRoute: CandidateJobsJobIdRoute,
  EmployerCandidateCandidateIdRoute: EmployerCandidateCandidateIdRoute,
  CandidateVerificationIndexRoute: CandidateVerificationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
