/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportCenterDataRouteImport } from './routes/support-center-data'
import { Route as SupportCenterRouteImport } from './routes/support-center'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as EmployerIndexRouteImport } from './routes/employer/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as EmployerProfileRouteImport } from './routes/employer/profile'
import { Route as EmployerPostJobRouteImport } from './routes/employer/post-job'
import { Route as EmployerChatRouteImport } from './routes/employer/chat'
import { Route as EmployerApplicantsRouteImport } from './routes/employer/applicants'
import { Route as CandidateShiftsRouteImport } from './routes/candidate/shifts'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateChatRouteImport } from './routes/candidate/chat'

const SupportCenterDataRoute = SupportCenterDataRouteImport.update({
  id: '/support-center-data',
  path: '/support-center-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCenterRoute = SupportCenterRouteImport.update({
  id: '/support-center',
  path: '/support-center',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer/profile',
  path: '/employer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPostJobRoute = EmployerPostJobRouteImport.update({
  id: '/employer/post-job',
  path: '/employer/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerChatRoute = EmployerChatRouteImport.update({
  id: '/employer/chat',
  path: '/employer/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicantsRoute = EmployerApplicantsRouteImport.update({
  id: '/employer/applicants',
  path: '/employer/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateShiftsRoute = CandidateShiftsRouteImport.update({
  id: '/candidate/shifts',
  path: '/candidate/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateChatRoute = CandidateChatRouteImport.update({
  id: '/candidate/chat',
  path: '/candidate/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/support-center': typeof SupportCenterRoute
  '/support-center-data': typeof SupportCenterDataRoute
  '/candidate/chat': typeof CandidateChatRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/shifts': typeof CandidateShiftsRoute
  '/employer/applicants': typeof EmployerApplicantsRoute
  '/employer/chat': typeof EmployerChatRoute
  '/employer/post-job': typeof EmployerPostJobRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/candidate/chat'
    | '/candidate/profile'
    | '/candidate/shifts'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/post-job'
    | '/employer/profile'
    | '/candidate/'
    | '/employer/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/candidate/chat'
    | '/candidate/profile'
    | '/candidate/shifts'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/post-job'
    | '/employer/profile'
    | '/candidate'
    | '/employer'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/support-center'
    | '/support-center-data'
    | '/candidate/chat'
    | '/candidate/profile'
    | '/candidate/shifts'
    | '/employer/applicants'
    | '/employer/chat'
    | '/employer/post-job'
    | '/employer/profile'
    | '/candidate/'
    | '/employer/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SupportCenterRoute: typeof SupportCenterRoute
  SupportCenterDataRoute: typeof SupportCenterDataRoute
  CandidateChatRoute: typeof CandidateChatRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateShiftsRoute: typeof CandidateShiftsRoute
  EmployerApplicantsRoute: typeof EmployerApplicantsRoute
  EmployerChatRoute: typeof EmployerChatRoute
  EmployerPostJobRoute: typeof EmployerPostJobRoute
  EmployerProfileRoute: typeof EmployerProfileRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-center-data': {
      id: '/support-center-data'
      path: '/support-center-data'
      fullPath: '/support-center-data'
      preLoaderRoute: typeof SupportCenterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-center': {
      id: '/support-center'
      path: '/support-center'
      fullPath: '/support-center'
      preLoaderRoute: typeof SupportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/profile': {
      id: '/employer/profile'
      path: '/employer/profile'
      fullPath: '/employer/profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/post-job': {
      id: '/employer/post-job'
      path: '/employer/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof EmployerPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/chat': {
      id: '/employer/chat'
      path: '/employer/chat'
      fullPath: '/employer/chat'
      preLoaderRoute: typeof EmployerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applicants': {
      id: '/employer/applicants'
      path: '/employer/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof EmployerApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/shifts': {
      id: '/candidate/shifts'
      path: '/candidate/shifts'
      fullPath: '/candidate/shifts'
      preLoaderRoute: typeof CandidateShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/chat': {
      id: '/candidate/chat'
      path: '/candidate/chat'
      fullPath: '/candidate/chat'
      preLoaderRoute: typeof CandidateChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SupportCenterRoute: SupportCenterRoute,
  SupportCenterDataRoute: SupportCenterDataRoute,
  CandidateChatRoute: CandidateChatRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateShiftsRoute: CandidateShiftsRoute,
  EmployerApplicantsRoute: EmployerApplicantsRoute,
  EmployerChatRoute: EmployerChatRoute,
  EmployerPostJobRoute: EmployerPostJobRoute,
  EmployerProfileRoute: EmployerProfileRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
